insert dictionaries values
('Angol-Magyar',
(SELECT languages.id from languages where languages.lang_name = 'UK English'),
(SELECT languages.id from languages where languages.lang_name = 'Magyar'),
GETDATE()),
('Német-Magyar',
(SELECT languages.id from languages where languages.lang_name = 'Deutsch'),
(SELECT languages.id from languages where languages.lang_name = 'Magyar'),
GETDATE()),
('Olasz-Magyar',
(SELECT languages.id from languages where languages.lang_name = 'Italiano'),
(SELECT languages.id from languages where languages.lang_name = 'Magyar'),
GETDATE()),
('Francia-Magyar',
(SELECT languages.id from languages where languages.lang_name = 'Francais'),
(SELECT languages.id from languages where languages.lang_name = 'Magyar'),
GETDATE()),
('Human Body (UK)',
(SELECT languages.id from languages where languages.lang_name = 'UK English'),
(SELECT languages.id from languages where languages.lang_name = 'Magyar'),
GETDATE());

insert words values
('1','apple','alma',3,1,GETDATE()),
('1','book','könny',3,1,GETDATE()),
('1','car','autó',3,1,GETDATE()),
('1','dictionary','szótár',3,1,GETDATE()),
('4','pome','alma',7,1,GETDATE()),
('4','amour','szerelem',7,1,GETDATE()),
('4','livre','könyv',7,1,GETDATE()),
('4','automobile','autó',7,1,GETDATE()),
('4','arbre','fa',7,1,GETDATE()),
('4','orange','narancs',7,1,GETDATE()),
('2','das Auto','autó',2,1,GETDATE()),
('2','das Buch','könyv',2,1,GETDATE()),
('2','die Autobahn','autópálya',2,1,GETDATE()),
('2','der Highway','autópálya',2,1,GETDATE()),
('2','die Schnellstraße','autópálya',2,1,GETDATE()),
('2','die Freiheit','szabadság',2,1,GETDATE()),
('2','die Birne','körte',2,1,GETDATE()),
('2','der Wald','erdő',2,1,GETDATE()),
('1','face','arc',3,1,GETDATE()),
('1','wrist','csukló',3,1,GETDATE()),
('1','head','fej',3,1,GETDATE()),
('1','shoulder','váll',3,1,GETDATE()),
('3','pomo','alma',10,1,GETDATE()),
('3','auto','autó',10,1,GETDATE()),
('3','pane','kenyér',10,1,GETDATE()),
('3','vigneto','szőlő',10,1,GETDATE()),
('3','formaggio','sajt',10,1,GETDATE()),
('3','cacio','sajt',10,1,GETDATE()),
('3','mare','tenger',10,1,GETDATE()),
('3','maggiore','nagyobb',10,1,GETDATE()),
('3','maggiore','idősebb',10,1,GETDATE()),
('5','head','fej',3,1,GETDATE()),
('5','tongue','nyelv',3,1,GETDATE()),
('5','ear','fül',3,1,GETDATE()),
('5','chest','mellkas',3,1,GETDATE()),
('5','fingers','ujjak',3,1,GETDATE()),
('5','wrist','csukló',3,1,GETDATE()),
('5','chin','áll',3,1,GETDATE()),
('5','stomach','has',3,1,GETDATE()),
('5','navel','köldök',3,1,GETDATE()),
('5','waist','derék',3,1,GETDATE()),
('5','cheek','orca',3,1,GETDATE()),
('5','face','arc',3,1,GETDATE()),
('5','elbow','könyök',3,1,GETDATE()),
('5','knee','térd',3,1,GETDATE()),
('5','heel','sarok',3,1,GETDATE()),
('5','forearm','alkar',3,1,GETDATE()),
('5','rim','talp',3,1,GETDATE()),
('5','hand','kéz',3,1,GETDATE()),
('5','hair','haj',3,1,GETDATE()),
('5','eyelashes','szempillák',3,1,GETDATE()),
('5','pupil','pupilla',3,1,GETDATE()),
('5','neck','nyak',3,1,GETDATE()),
('5','eyelid','szemhéj',3,1,GETDATE()),
('5','lip','ajak',3,1,GETDATE()),
('5','mouth','száj',3,1,GETDATE()),
('5','nose','orr',3,1,GETDATE()),
('5','iris','írisz',3,1,GETDATE()),
('5','eyebrow','szemöldök',3,1,GETDATE()),
('5','forehead','homlok',3,1,GETDATE()),
('5','The wite of the eye','szemfehérje',3,1,GETDATE()),
('5','shoulder','váll',3,1,GETDATE()),
('5','armpit','hónalj',3,1,GETDATE()),
('5','back','hát',3,1,GETDATE()),
('5','buttocks','fenék',3,1,GETDATE()),
('5','calf','vádli',3,1,GETDATE()),
('5','shin','lábszár, sípcsont',3,1,GETDATE());
